const KI_SummaryCard = {
  buildData(session) {
    return {
      channelName: session.channelName,
      date: KI_Format.formatDate(session.startTime),
      duration: KI_Format.formatDuration(session.duration),
      avgKick: KI_Format.compactNumber(session.summary.avgKickCount),
      avgEstimated: KI_Format.compactNumber(session.summary.avgEstimatedCount),
      peakEstimated: KI_Format.compactNumber(session.summary.peakEstimated),
      totalUniqueChatters: KI_Format.compactNumber(session.summary.totalUniqueChatters),
      censusCount: session.censuses.length,
      snapshots: session.snapshots,
    };
  },

  render(canvas, session) {
    const data = this.buildData(session);
    const ctx = canvas.getContext('2d');
    const w = canvas.width;
    const h = canvas.height;

    ctx.fillStyle = '#0e0e10';
    ctx.fillRect(0, 0, w, h);

    ctx.strokeStyle = '#2a2a2e';
    ctx.lineWidth = 2;
    ctx.strokeRect(1, 1, w - 2, h - 2);

    ctx.fillStyle = '#53fc18';
    ctx.font = 'bold 20px system-ui';
    ctx.fillText(data.channelName, 24, 40);

    ctx.fillStyle = '#888';
    ctx.font = '13px system-ui';
    ctx.fillText(`${data.date}  |  ${data.duration}`, 24, 62);

    ctx.strokeStyle = '#2a2a2e';
    ctx.beginPath();
    ctx.moveTo(24, 76);
    ctx.lineTo(w - 24, 76);
    ctx.stroke();

    const midX = w / 2;

    ctx.fillStyle = '#888';
    ctx.font = '11px system-ui';
    ctx.textAlign = 'center';
    ctx.fillText('KICK DISPLAYED', midX - 120, 106);
    ctx.fillStyle = '#f97316';
    ctx.font = 'bold 36px system-ui';
    ctx.fillText(data.avgKick, midX - 120, 148);

    ctx.fillStyle = '#444';
    ctx.font = '14px system-ui';
    ctx.fillText('vs', midX, 130);

    ctx.fillStyle = '#888';
    ctx.font = '11px system-ui';
    ctx.fillText('ESTIMATED REAL', midX + 120, 106);
    ctx.fillStyle = '#10b981';
    ctx.font = 'bold 36px system-ui';
    ctx.fillText(data.avgEstimated, midX + 120, 148);

    if (data.snapshots.length >= 2) {
      const sparkY = 180;
      const sparkH = 80;
      const sparkW = w - 48;
      const sparkX = 24;

      const estCounts = data.snapshots.map(s => s.estimatedCount);
      const kickCounts = data.snapshots.map(s => s.kickCount);
      const maxVal = Math.max(...estCounts, ...kickCounts) * 1.1 || 1;
      const stepX = sparkW / (data.snapshots.length - 1);

      ctx.beginPath();
      ctx.strokeStyle = '#f9731644';
      ctx.lineWidth = 1.5;
      for (let i = 0; i < kickCounts.length; i++) {
        const x = sparkX + i * stepX;
        const y = sparkY + sparkH - (kickCounts[i] / maxVal) * sparkH;
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      }
      ctx.stroke();

      ctx.beginPath();
      ctx.strokeStyle = '#10b981';
      ctx.lineWidth = 2;
      for (let i = 0; i < estCounts.length; i++) {
        const x = sparkX + i * stepX;
        const y = sparkY + sparkH - (estCounts[i] / maxVal) * sparkH;
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      }
      ctx.stroke();
    }

    ctx.textAlign = 'left';
    ctx.fillStyle = '#666';
    ctx.font = '11px system-ui';
    ctx.fillText(`Peak: ${data.peakEstimated}  |  Unique chatters: ${data.totalUniqueChatters}  |  Censuses: ${data.censusCount}`, 24, 290);

    ctx.strokeStyle = '#2a2a2e';
    ctx.beginPath();
    ctx.moveTo(24, 310);
    ctx.lineTo(w - 24, 310);
    ctx.stroke();

    ctx.fillStyle = '#333';
    ctx.font = '11px system-ui';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by KickInsights', midX, 340);

    ctx.textAlign = 'left';
  },
};

if (typeof module !== 'undefined') module.exports = { KI_SummaryCard };
